---
kind: pipeline
type: docker
name: build

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps: 
- name: build-backend
  image: plugins/docker
  environment:
    TAG:
      ${DRONE_TAG}
    COMMIT:
      ${DRONE_COMMIT}
  settings:
    insecure: true
    repo: registry.internal.aw/simrail-backend
    registry: registry.internal.aw
    context: './packages/backend'
    dockerfile: './packages/backend/Dockerfile'
    build_args_from_env:
      - TAG
      - COMMIT
    tags:
      - latest
      - ${DRONE_TAG##v}
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

- name: build-frontend
  image: plugins/docker
  environment:
    VITE_API_URL:
      from_secret: VITE_API_URL
    VITE_STATS_KEY:
      from_secret: VITE_STATS_KEY
  settings:
    insecure: true
    repo: registry.internal.aw/simrail-frontend
    registry: registry.internal.aw
    context: './packages/frontend'
    dockerfile: './packages/frontend/Dockerfile'
    build_args_from_env:
        - VITE_API_URL
        - VITE_STATS_KEY
    tags:
      - latest
      - ${DRONE_TAG##v}
  volumes:
    - name: dockersock
      path: /var/run/docker.sock

trigger:
  event:
  - tag