---
kind: pipeline
type: docker
name: build

steps: 
- name: build-backend
  image: plugins/docker
  settings:
    insecure: true
    repo: 10.5.0.103:1222/simrail-backend
    registry: 10.5.0.103:1222
    context: './packages/backend'
    tags:
      - latest

- name: build-frontend
  image: plugins/docker
  settings:
    insecure: true
    repo: 10.5.0.103:1222/simrail-frontend
    registry: 10.5.0.103:1222
    context: './packages/frontend'
    tags:
      - latest

trigger:
  branch:
  - main
