services:
  simrail-backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped

  simrail-frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_STATS_KEY: ${VITE_STATS_KEY}
    restart: unless-stopped
